AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Antipode Lambda - MySQL<>SNS - Writer
Parameters:
  ANTIPODE:
    Type: Number
    Description: Antipode enabled (1) or not (0)
    Default: 0
Resources:
  AntipodeLambdaMysqlSnsWriter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: writer.lambda_handler
      Runtime: python3.7
      Description: 'Antipode Lambda - MySQL<>SNS - Writer'
      MemorySize: 128
      Timeout: 900
      Role: arn:aws:iam::641424397462:role/antipode-lambda-admin
      Environment:
        Variables:
          ANTIPODE: !Ref ANTIPODE
          MYSQL_HOST: antipode-lambda-eu.cluster-citztxl8ztvl.eu-central-1.rds.amazonaws.com
          MYSQL_PORT: 3306
          MYSQL_USER: antipode
          MYSQL_PASSWORD: antipode
          MYSQL_DB: antipode
          MYSQL_POST_TABLE_NAME: blobs
          MYSQL_NOTIFICATIONS_TABLE_NAME: keyvalue
          SNS_ARN: arn:aws:sns:eu-central-1:641424397462:antipode-lambda-notifications
      # We tried with this but somehow it DID NOT send messages to the topic
      # EventInvokeConfig:
      #   DestinationConfig:
      #     OnSuccess:
      #       Type: SNS
      #       Destination: arn:aws:sns:eu-central-1:641424397462:antipode-lambda-notifications
